name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: .NET Publish
      run: |
        dotnet publish AfterRenderExecution.csproj -c Release --nologo -p:PublishTrimmed=true -o release
        sed -i 's/<base href="\/" \/>/<base href="\/Blazor-AfterRenderExecution\/" \/>/g' release/wwwroot/index.html

    - name: Commit to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
